### ISSUE TITLE
Release with Python 3.9

### ISSUE THREAD

**Issue by magdalenafuentes** [meinardmueller/synctoolbox#12]
Just as a reminder, since the release in pip right now is not working with `python 3.9`. In a conda environment with that python version I'm getting:

```
(joss_review) cusp-vmn244:repos mf3734$ pip install synctoolbox
ERROR: Could not find a version that satisfies the requirement synctoolbox (from versions: none)
ERROR: No matching distribution found for synctoolbox
```

Related to #6

openjournals/joss-reviews#3434

**Comment by yiitozer** [comment]
Dear @magdalenafuentes, I launched a new release. The new release is compatible with python3.9:
https://pypi.org/project/synctoolbox/1.0.1/
