### ISSUE TITLE
Issues with soundfile when installing Sync Toolbox 

### ISSUE THREAD

**Issue by ahnonay** [meinardmueller/synctoolbox#3]
This issue arised for @lutzhamel during the JOSS review process, see also:
https://github.com/openjournals/joss-reviews/issues/3434

In some cases when installing synctoolbox via pip, one gets errors related to ``soundfile`` which is a dependency of ``librosa``. 

We hope to have addressed this issue in the latest commits on the master branch in two ways:
- The example notebooks can now be run inside the browser using Binder, no installation necessary.
- We have added additional explanations for users who want to install the toolbox locally. In particular, the issues with soundfile can usually be solved by running ``sudo apt install libsndfile1``

Dear @lutzhamel, thanks for making us aware of this problem. Please let us know if the latest changes have solved this for you.

**Comment by lutzhamel** [comment]
Installing `libsndfile1` on Ubuntu 20.04 did the trick.  I was able to run the `sync_audio_audio_simple.ipynb` and the `sync_audio_score_full.ipynb` locally on the linux system.

**Comment by ahnonay** [comment]
Happy to hear that! I'll close this issue for now. Please reopen, if you think this is not yet resolved.
Regarding the remaining problems related to rubberband, please see my response in
openjournals/joss-reviews#3434
