### ISSUE TITLE
Enable continous integration

### ISSUE THREAD

**Issue by faroit** [meinardmueller/synctoolbox#5]
to solve installation issues it could help to include a number of continuous integration tests that run

* runs the unit tests and installs the package 
* test the package installation in a conda environment using different python versions

https://github.com/openjournals/joss-reviews/issues/3434

**Comment by yiitozer** [comment]
I created a workflow which runs the unit tests in a conda environment using python 3.8 version:
https://github.com/meinardmueller/synctoolbox/actions/runs/1070732431

Would it be necessary to have two more workflows for python 3.7 and 3.9 versions?

**Comment by faroit** [comment]
great!

> Would it be necessary to have two more workflows for python 3.7 and 3.9 versions?

i usually test multiple python version for the pip tests and only a single one conda test because the conda workflows aren't that quick and do not cache that well..

See [this example](https://github.com/sigsep/open-unmix-pytorch/blob/master/.github/workflows/test_cli.yml) how run matrix builds with different python version using a single workflow

**Comment by yiitozer** [comment]
Thank you, the example has been very helpful.

I created two pull requests following your instructions:
https://github.com/meinardmueller/synctoolbox/pulls


I will merge them if you confirm it.

**Comment by faroit** [comment]
@yiitozer both look good to me. 

Just noted: there are a bunch of deprecations shown in the unit tests when running with numpy 1.20 (See [here](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations)). I would expect this package would break with a future numpy version soon, so better to fix this sooner rather than later

**Comment by yiitozer** [comment]
@faroit, thank you for pointing it out. I fixed it!

**Comment by yiitozer** [comment]
Can we close this issue?

**Comment by faroit** [comment]
yep. thanks!
